INSERT INTO department(department_name) VALUES ('Sale');
INSERT INTO department(department_name) VALUES ('Marketing');
INSERT INTO department(department_name) VALUES ('HR');
INSERT INTO department(department_name) VALUES ('IT');
INSERT INTO department(department_name) VALUES ('Finance');
INSERT INTO department(department_name) VALUES ('QA');
INSERT INTO department(department_name) VALUES ('Security');
INSERT INTO department(department_name) VALUES ('Operation');
INSERT INTO department(department_name) VALUES ('Support');
INSERT INTO department(department_name) VALUES ('R&D');
INSERT INTO department(department_name) VALUES ('Training');
INSERT INTO department(department_name) VALUES ('Legal');
INSERT INTO department(department_name) VALUES ('Admin');
INSERT INTO department(department_name) VALUES ('Purchasing');
INSERT INTO department(department_name) VALUES ('Logistics');
INSERT INTO department(department_name) VALUES ('Customer Service');
INSERT INTO department(department_name) VALUES ('Business');
INSERT INTO department(department_name) VALUES ('Product');
INSERT INTO department(department_name) VALUES ('Data');
INSERT INTO department(department_name) VALUES ('PMO');
INSERT INTO `position`(position_id,position_name) VALUES (1,'DEV');
INSERT INTO `position`(position_id,position_name) VALUES (2,'TEST');
INSERT INTO `position`(position_id,position_name) VALUES (3,'SCRUM_MASTER');
INSERT INTO `position`(position_id,position_name) VALUES (4,'PM');
INSERT INTO `position`(position_id,position_name) VALUES (5,'DEV');
INSERT INTO `position`(position_id,position_name) VALUES (6,'TEST');
INSERT INTO `position`(position_id,position_name) VALUES (7,'SCRUM_MASTER');
INSERT INTO `position`(position_id,position_name) VALUES (8,'PM');
INSERT INTO `position`(position_id,position_name) VALUES (9,'DEV');
INSERT INTO `position`(position_id,position_name) VALUES (10,'TEST');
INSERT INTO `position`(position_id,position_name) VALUES (11,'SCRUM_MASTER');
INSERT INTO `position`(position_id,position_name) VALUES (12,'PM');
INSERT INTO `position`(position_id,position_name) VALUES (13,'DEV');
INSERT INTO `position`(position_id,position_name) VALUES (14,'TEST');
INSERT INTO `position`(position_id,position_name) VALUES (15,'SCRUM_MASTER');
INSERT INTO `position`(position_id,position_name) VALUES (16,'PM');
INSERT INTO `position`(position_id,position_name) VALUES (17,'DEV');
INSERT INTO `position`(position_id,position_name) VALUES (18,'TEST');
INSERT INTO `position`(position_id,position_name) VALUES (19,'SCRUM_MASTER');
INSERT INTO `position`(position_id,position_name) VALUES (20,'PM');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user1@mail.com','user1','User 1',4,1,'2010-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user2@mail.com','user2','User 2',4,2,'2011-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user3@mail.com','user3','User 3',4,3,'2012-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user4@mail.com','user4','User 4',4,4,'2013-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user5@mail.com','user5','User 5',4,5,'2014-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user6@mail.com','user6','User 6',6,1,'2015-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user7@mail.com','user7','User 7',6,2,'2016-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user8@mail.com','user8','User 8',6,3,'2017-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user9@mail.com','user9','User 9',6,2,'2018-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user10@mail.com','user10','User 10',10,6,'2019-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user11@mail.com','user11','User 11',10,10,'2020-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user12@mail.com','user12','User 12',10,14,'2021-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user13@mail.com','user13','User 13',13,18,'2022-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user14@mail.com','user14','User 14',14,3,'2023-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user15@mail.com','user15','User 15',15,7,'2024-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user16@mail.com','user16','User 16',16,11,'2025-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user17@mail.com','user17','User 17',17,15,'2026-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user18@mail.com','user18','User 18',18,4,'2027-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user19@mail.com','user19','User 19',19,8,'2028-01-15 09:00:00');
INSERT INTO `account`(email,username,fullname,department_id,position_id,create_date) VALUES ('user20@mail.com','user20','User 20',20,12,'2029-01-15 09:00:00');
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 1',1);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 2',2);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 3',3);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 4',4);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 5',5);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 6',6);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 7',7);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 8',8);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 9',9);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 10',10);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 11',11);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 12',12);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 13',13);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 14',14);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 15',15);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 16',16);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 17',17);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 18',18);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 19',19);
INSERT INTO `group`(group_name,creator_id) VALUES ('Group 20',20);
INSERT INTO group_account(group_id,account_id) VALUES (1,1);
INSERT INTO group_account(group_id,account_id) VALUES (1,2);
INSERT INTO group_account(group_id,account_id) VALUES (1,3);
INSERT INTO group_account(group_id,account_id) VALUES (1,4);
INSERT INTO group_account(group_id,account_id) VALUES (1,5);
INSERT INTO group_account(group_id,account_id) VALUES (1,6);
INSERT INTO group_account(group_id,account_id) VALUES (1,7);
INSERT INTO group_account(group_id,account_id) VALUES (1,8);
INSERT INTO group_account(group_id,account_id) VALUES (2,2);
INSERT INTO group_account(group_id,account_id) VALUES (2,3);
INSERT INTO group_account(group_id,account_id) VALUES (2,4);
INSERT INTO group_account(group_id,account_id) VALUES (2,5);
INSERT INTO group_account(group_id,account_id) VALUES (2,6);
INSERT INTO group_account(group_id,account_id) VALUES (2,7);
INSERT INTO group_account(group_id,account_id) VALUES (3,3);
INSERT INTO group_account(group_id,account_id) VALUES (3,4);
INSERT INTO group_account(group_id,account_id) VALUES (3,5);
INSERT INTO group_account(group_id,account_id) VALUES (3,6);
INSERT INTO group_account(group_id,account_id) VALUES (3,7);
INSERT INTO group_account(group_id,account_id) VALUES (3,8);
INSERT INTO group_account(group_id,account_id) VALUES (3,9);
INSERT INTO group_account(group_id,account_id) VALUES (4,4);
INSERT INTO group_account(group_id,account_id) VALUES (4,5);
INSERT INTO group_account(group_id,account_id) VALUES (5,5);
INSERT INTO group_account(group_id,account_id) VALUES (5,6);
INSERT INTO group_account(group_id,account_id) VALUES (5,7);
INSERT INTO group_account(group_id,account_id) VALUES (6,6);
INSERT INTO group_account(group_id,account_id) VALUES (6,7);
INSERT INTO group_account(group_id,account_id) VALUES (6,8);
INSERT INTO group_account(group_id,account_id) VALUES (7,7);
INSERT INTO group_account(group_id,account_id) VALUES (7,8);
INSERT INTO group_account(group_id,account_id) VALUES (7,9);
INSERT INTO group_account(group_id,account_id) VALUES (8,8);
INSERT INTO group_account(group_id,account_id) VALUES (8,9);
INSERT INTO group_account(group_id,account_id) VALUES (8,10);
INSERT INTO group_account(group_id,account_id) VALUES (9,9);
INSERT INTO group_account(group_id,account_id) VALUES (9,10);
INSERT INTO group_account(group_id,account_id) VALUES (9,11);
INSERT INTO group_account(group_id,account_id) VALUES (10,10);
INSERT INTO group_account(group_id,account_id) VALUES (10,11);
INSERT INTO group_account(group_id,account_id) VALUES (10,12);
INSERT INTO group_account(group_id,account_id) VALUES (11,11);
INSERT INTO group_account(group_id,account_id) VALUES (11,12);
INSERT INTO group_account(group_id,account_id) VALUES (11,13);
INSERT INTO group_account(group_id,account_id) VALUES (12,12);
INSERT INTO group_account(group_id,account_id) VALUES (12,13);
INSERT INTO group_account(group_id,account_id) VALUES (12,14);
INSERT INTO group_account(group_id,account_id) VALUES (13,13);
INSERT INTO group_account(group_id,account_id) VALUES (13,14);
INSERT INTO group_account(group_id,account_id) VALUES (13,15);
INSERT INTO group_account(group_id,account_id) VALUES (14,14);
INSERT INTO group_account(group_id,account_id) VALUES (14,15);
INSERT INTO group_account(group_id,account_id) VALUES (14,16);
INSERT INTO group_account(group_id,account_id) VALUES (15,15);
INSERT INTO group_account(group_id,account_id) VALUES (15,16);
INSERT INTO group_account(group_id,account_id) VALUES (15,17);
INSERT INTO group_account(group_id,account_id) VALUES (16,16);
INSERT INTO group_account(group_id,account_id) VALUES (16,17);
INSERT INTO group_account(group_id,account_id) VALUES (16,18);
INSERT INTO group_account(group_id,account_id) VALUES (17,17);
INSERT INTO group_account(group_id,account_id) VALUES (17,18);
INSERT INTO group_account(group_id,account_id) VALUES (17,19);
INSERT INTO group_account(group_id,account_id) VALUES (18,18);
INSERT INTO group_account(group_id,account_id) VALUES (18,19);
INSERT INTO group_account(group_id,account_id) VALUES (18,20);
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO type_question(type_name) VALUES ('ESSAY');
INSERT INTO type_question(type_name) VALUES ('MULTIPLE_CHOICE');
INSERT INTO category_question(category_name) VALUES ('Java');
INSERT INTO category_question(category_name) VALUES ('SQL');
INSERT INTO category_question(category_name) VALUES ('C#');
INSERT INTO category_question(category_name) VALUES ('Python');
INSERT INTO category_question(category_name) VALUES ('Spring');
INSERT INTO category_question(category_name) VALUES ('Hibernate');
INSERT INTO category_question(category_name) VALUES ('Database');
INSERT INTO category_question(category_name) VALUES ('Linux');
INSERT INTO category_question(category_name) VALUES ('Network');
INSERT INTO category_question(category_name) VALUES ('HTML');
INSERT INTO category_question(category_name) VALUES ('CSS');
INSERT INTO category_question(category_name) VALUES ('JavaScript');
INSERT INTO category_question(category_name) VALUES ('Git');
INSERT INTO category_question(category_name) VALUES ('Docker');
INSERT INTO category_question(category_name) VALUES ('Kubernetes');
INSERT INTO category_question(category_name) VALUES ('AWS');
INSERT INTO category_question(category_name) VALUES ('Azure');
INSERT INTO category_question(category_name) VALUES ('Security');
INSERT INTO category_question(category_name) VALUES ('Algorithm');
INSERT INTO category_question(category_name) VALUES ('Testing');
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 1',1,1,1);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 2',2,2,2);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 3',3,3,3);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 4',4,4,4);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 5',5,5,5);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 6',6,6,6);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 7',7,7,7);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 8',8,8,8);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 9',9,9,9);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 10',10,10,10);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 11',11,11,11);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 12',12,12,12);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 13',13,13,13);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 14',14,14,14);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 15',15,15,15);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 16',16,16,16);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 17',17,17,17);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 18',18,18,18);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 19',19,19,19);
INSERT INTO question(content,category_id,type_id,creator_id) VALUES ('Question 20',20,20,20);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 1',1,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 2',1,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 3',1,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 4',1,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 5',1,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 6',2,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 7',2,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 8',2,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 9',2,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 10',3,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 11',3,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 12',3,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 13',4,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 14',4,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 15',4,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 16',5,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 17',5,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 18',5,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 19',6,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 20',6,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 21',6,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 22',7,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 23',7,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 24',7,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 25',8,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 26',8,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 27',8,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 28',9,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 29',9,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 30',9,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 31',10,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 32',10,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 33',11,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 34',11,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 35',12,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 36',12,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 37',13,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 38',13,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 39',14,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 40',14,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 41',15,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 42',15,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 43',16,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 44',16,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 45',17,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 46',17,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 47',18,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 48',18,FALSE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 49',19,TRUE);
INSERT INTO answer(content,question_id,is_correct) VALUES ('Answer 50',19,FALSE);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1001,'Exam 1',1,'01:00:00',1);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1002,'Exam 2',2,'01:00:00',2);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1003,'Exam 3',3,'01:00:00',3);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1004,'Exam 4',4,'01:00:00',4);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1005,'Exam 5',5,'01:00:00',5);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1006,'Exam 6',6,'01:00:00',6);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1007,'Exam 7',7,'01:00:00',7);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1008,'Exam 8',8,'01:00:00',8);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1009,'Exam 9',9,'01:00:00',9);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1010,'Exam 10',10,'01:00:00',10);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1011,'Exam 11',11,'01:00:00',11);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1012,'Exam 12',12,'01:00:00',12);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1013,'Exam 13',13,'01:00:00',13);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1014,'Exam 14',14,'01:00:00',14);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1015,'Exam 15',15,'01:00:00',15);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1016,'Exam 16',16,'01:00:00',16);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1017,'Exam 17',17,'01:00:00',17);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1018,'Exam 18',18,'01:00:00',18);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1019,'Exam 19',19,'01:00:00',19);
INSERT INTO exam(code,title,category_id,duration,creator_id) VALUES (1020,'Exam 20',20,'01:00:00',20);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,1);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,2);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,3);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,4);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,5);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,6);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,7);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (1,8);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (2,2);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (2,3);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (2,4);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (2,5);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (2,6);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (2,7);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (3,3);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (3,4);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (3,5);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (3,6);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (3,7);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (4,4);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (4,5);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (4,6);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (5,5);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (5,6);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (5,7);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (6,6);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (6,7);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (6,8);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (7,7);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (7,8);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (7,9);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (8,8);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (8,9);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (8,10);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (9,9);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (9,10);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (9,11);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (10,10);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (10,11);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (10,12);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (11,11);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (11,12);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (11,13);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (12,12);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (12,13);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (12,14);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (13,13);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (13,14);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (13,15);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (14,14);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (14,15);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (14,16);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (15,15);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (15,16);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (15,17);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (16,16);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (16,17);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (16,18);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (17,17);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (17,18);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (17,19);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (18,18);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (18,19);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (18,20);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (19,19);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (19,20);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (19,1);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (20,20);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (20,1);
INSERT IGNORE INTO exam_question(exam_id,question_id) VALUES (20,2);